# We can have from zero to many running subscribers
# Each subscriber binds to these ports on all interfaces
subscriber:
  - addr: "94.156.25.224"
    ports: "5000-5150"

# We have only one publisher that sends blocks to its subscribers
publisher:
