subscriber:


# We have only one publisher that sends blocks to its subscribers
publisher:
  #- addr: "94.156.178.66"
  #   ports: "5001-5100"
  - addr_listen: "94.156.178.64"
    addr_peer: "94.156.25.224"
    ports: "5000-5019"